{% set name = "snakebite-py3" %}
{% set version = "3.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snakebite-py3-{{ version }}.tar.gz
  sha256: 2026f2f755b63503145b6ab3037ca2b5905c9d1c68d3e7903b90ab94ac7fa260
  patches:
    - 0001-remove-argparse.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [py<36]

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - pip
    - setuptools
    - wheel
    - python
  run:
    - protobuf >2.4.1
    - python

test:
  imports:
    - snakebite
    - snakebite.protobuf
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/internetarchive/snakebite-py3
  summary: Pure Python HDFS client
  description: |
    Port of snakebite for python 3.

    Snakebite is a python library that provides a pure python HDFS client and a
    wrapper around Hadoops minicluster. The client uses protobuf for
    communicating with the NameNode and comes in the form of a library and a
    command line interface. Currently, the snakebite client supports most
    actions that involve the Namenode and reading data from DataNodes.

  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/internetarchive/snakebite-py3
  dev_url: https://github.com/internetarchive/snakebite-py3

extra:
  recipe-maintainers:
    - xylar
